services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=http://localhost:8180
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=8180
      - KC_HOSTNAME_STRICT_BACKCHANNEL=false
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HEALTH_ENABLED=true
    command: start-dev
    ports:
      - "8180:8080"
    restart: always
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - appnet

  postgres:
    image: postgres:15
    container_name: postgres_db_new
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: NewDbComputer
    ports:
      - "5432:5432" #port d'écoute l'hote et port du conteneur
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet

  api-gateway:
    build: ./APIGateway
    container_name: api_gateway_efrei
    ports:
      - "5005:5005" #port d'écoute l'hote et port du conteneur
    depends_on:
      - weather-service
    networks:
      - appnet

  weather-service:
    build:
      context: .
      dockerfile: WeatherAPI/Dockerfile
    container_name: weather_service
    ports:
      - "5001:5001" #port d'écoute l'hote et port du conteneur
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__Default=Host=host.docker.internal;Port=5432;Database=NewDbComputer;Username=user;Password=1234
    networks:
      - appnet

  keycloak-auth-service:
    build:
      context: .
      dockerfile: KeycloakAuthService/Dockerfile
    container_name: keycloak_auth_service_new
    ports:
      - "5051:5051" #port d'écoute l'hote et port du conteneur
    networks:
      - appnet

volumes:
  postgres_data:
  keycloak_data:

networks:
  appnet:
    driver: bridge


